<?xml version="1.0" encoding="UTF-8"?>

<!-- ELEMENT를 정의할 때, 하위 엘리먼트의 포함관계를 명시할 때, 열거형(,)이나 선택(|)관계를 표기할 수 있다. -->
<!-- 내부 DTD 선언 -->
<!DOCTYPE products [
    <!ELEMENT product (prodCode, prodName, (price | quantity), comapny)>
        <!ELEMENT prodCode  (#PCDATA)>
        <!ELEMENT prodName  (#PCDATA)>
        <!ELEMENT price     (#PCDATA)>
        <!ELEMENT quantity  (#PCDATA)>
        <!ELEMENT company   (employee, empNo)*>
        
    <!ELEMENT employee  (#PCDATA)>
    <!ELEMENT empNo     (#PCDATA)>
]>

<!-- 
Product adidas = new Product("S001", "슈퍼스타", 87200, 5);
Product reebok = new Product("S002", "리복 로얄 테크큐 티", 42000, 20);
Product nike = new Product("S003", "나이키 탄준 샌들", 41300, 30);
Product crocs = new Product("S004", "라이트라이드 샌들 우먼", 40200, 7);
Product birkenstock = new Product("S005", "지제 에바", 29000, 15);
 -->

<products>
    <product>
        <prodCode>S001</prodCode>
        <prodName>adidas</prodName>
        <price>87200</price>
        <company/>
        <!-- *연산자에 의해 하위 엘리먼트가 없어도 괜찮음. -->
    </product>
    <product>
        <prodCode>S002</prodCode>
        <prodName>reebok</prodName>
        <quantity>20</quantity>
        <company>
            <employee>김길동</employee>
            <empNo>9999</empNo>
        </company>
        <!-- 규칙에 의해서, employee가 있으면 반드시 empNo도 있어야 한다. -->
    </product>
    <product>
        <prodCode>S003</prodCode>
        <prodName>nike</prodName>
        <price>41300</price>
         <company>
            <employee>홍길동</employee>
            <empNo>1111</empNo>
            <employee>허균</employee>
            <empNo>2222</empNo>
        </company>
    </product>
</products>